#!/usr/bin/env bash
#bash script that configures nginx
apt-get update
apt-get -y install nginx
echo "server {
    listen 80;
    location / {
        echo 'hello world!';
    }
}" | sudo tee /etc/nginx/sites-available/default
ufw allow 'Nginx HTTP'
service nginx start 
