#!/usr/bin/env bash
#permanent redirection
link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_conf="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default
sudo service nginx start
